name: Monitor and Re-run Workflow

on:
  workflow_run:
    workflows: ["last"]
    types:
      - completed

jobs:
  check_status:
    runs-on: ubuntu-latest
    steps:
      - name: Check Workflow Run Status
        run: |
          if [[ "${{ github.event.workflow_run.conclusion }}" == "cancelled" ]]; then
            echo "The workflow was canceled. Re-running the workflow."
            curl -X POST \
              -H "Authorization: token ${{ secrets.MY_GITHUB_TOKEN }}" \
              -d '{"event_type": "rerun"}' \
              "https://api.github.com/repos/${{ github.repository }}/dispatches"
          else
            echo "Workflow completed successfully or failed, no action needed."
          fi
